spring.application.name=jira

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/jira}

server.port=${PORT:8080}

cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000}
